config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions do
    member do
      get "follow_users"
      get "follow_topic"
    end
  end
  devise_for :users
  root to: "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow_topic.rb
class FollowTopic < ApplicationRecord
  belongs_to :topic
end

app/models/follow_user.rb
class FollowUser < ApplicationRecord
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :answers

  def topics
    topics = FollowTopic.where(user_id: self.id).pluck(:topic_id)
    Topic.where(id: topics)
  end

  def following
    users = FollowUser.where(user_id: self.id).pluck(:follow_id)
    User.where(id: users)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:edit, :update]
  before_action :authenticate_user!

  # GET /answers/new
  def new
    @answer = Answer.new
    @question_id = params[:question_id]
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to question_path(id: @answer.question_id), notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.

    def answer_params
      params.require(:answer).permit(:user_id, :solution, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = Answer.where(question_id: params[:id])
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow_users
    following_user = User.find_by(id: params[:follow_id])
    already_followed = FollowUser.find_by(user_id: following_user.id, follow_id: current_user.id) if following_user.present?
    if following_user.present? && !already_followed.present?
      FollowUser.create(user_id: following_user.id, follow_id: current_user.id)
      redirect_to question_path(id: params[:id]), notice: "Successfully Followed"
    elsif following_user.present? && already_followed.present?
      redirect_to question_path(id: params[:id]), alert: "Already following"
    else
      redirect_to question_path(id: params[:id]), alert: "User not found"
    end

  end

  def follow_topic
    following_topic = Topic.find_by(id: params[:topic_id])
    already_followed = FollowTopic.find_by(user_id: current_user.id, topic_id: following_topic.id) if following_topic.present?
    if following_topic.present? && !already_followed.present?
      FollowTopic.create(user_id: current_user.id, topic_id: following_topic.id)
      redirect_to question_path(id: params[:id]) , notice: "Successfully Followed"
    elsif following_topic.present? && already_followed.present?
      redirect_to question_path(id: params[:id]), alert: "Already following"
    else
      redirect_to question_path(id: params[:id]), alert: "Topic not found"
    end

  def add_answer
  end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:ques, :topic_id)
    end
    def answer_params
      params.require(:answer).permit(:user_id, :solution, :question_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_name(id)
    user = User.find_by(id: id)
    return user.name if user.present?
    return ""
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :solution %>
  </div>

  <%=form.hidden_field :question_id, value: @question_id%>
  <%=form.hidden_field :user_id, value: current_user.id%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/home/index.html.erb
<h1> List of Questions</h1>

<% @questions.each do |question|%>
  <h3><%= link_to question.try(:ques), question_path(question.id)%></h3>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignmentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <%if alert == "Invalid Email or password."%>
      <p class="alert"> Username/Password incorrect</p>
    <%else%>
      <p class="alert"><%= alert%></p>
    <%end%>

    <% if user_signed_in? %>
      <div class="logout"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

<style>
  .logout {
    float: right;
    font-size: initial;
}
  </style>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :ques %>
  </div>

<div class="field">
  <%= form.label :topic %>
  <%= form.collection_select :topic_id, Topic.all, :id, :name, include_blank: false %>

</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <h3><%= link_to question.try(:ques), question%></h3>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="add_new_question"><%= link_to 'Add New Question', new_question_path %></div>

<style>
  .add_new_question {
    text-align: center;
    font-size: initial;
}
  </style>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.ques %>
</p>

<p>
<strong> Answers list</strong>
</p>

  <%@answers.each do |ans|%>
  <li>
    <%= ans.solution%> Posted_by <b><%=user_name(ans.user_id)%></b><br><br>
    </li>
  <%end%>

<%= link_to 'Add your answer', new_answer_path(question_id: @question.id) %><br><br>
<div class="follow_user"><%= link_to 'Follow User', follow_users_question_path(id: @question.id, follow_id: @question.user_id)%><br><br></div>
<div class="follow_topic"><%= link_to 'Follow Topic', follow_topic_question_path(id: @question.id, topic_id: @question.topic_id)%><br></br></div>
<%= link_to 'Back', questions_path %>